### ISSUE TITLE
Strange way of treating purs ADT values in FFI

### ISSUE THREAD

**Issue by wclr** [keijokapp/purescript-web-cssom-view#10]
https://github.com/purescript-web/purescript-web-cssom-view/blob/master/src/Web/CSSOMView/Element.js#L2

This is definitely not the way it should be done, it cannot depend on such implementation details, moreover it works incorrectly.

**Comment by keijokapp** [comment]
Thanks for reporting the broken functionality. I'm closing this as a duplicate of #7. I also created PR #11 which should solve both issues.

**Comment by wclr** [comment]
Thanks, hope to see it fixed soon.
