### ISSUE TITLE
Move the library to purescript-web namespace

### ISSUE THREAD

**Issue by keijokapp** [keijokapp/purescript-web-cssom-view#3]
If anyone lands here who can help with that, please let me know.

**Comment by garyb** [comment]
👋 better late than never? 😉 

I'll send you an invite to the `purescript-web` organization, and then you'll have the ability to move it over.

**Comment by keijokapp** [comment]
Hi! Thanks, I've moved it over.

Now it needs to be published on Pursuit but before that it would need some maintenance work (fixing open issues and updating dependencies). Since I don't use PureScript anymore, it takes some time to test these changes.

I'd keep this issue open until the package is published.

**Comment by JordanMartinez** [comment]
This has been transferred but the Registry likely needs to be updated.

**Comment by keijokapp** [comment]
This package depends on https://github.com/keijokapp/purescript-web-geometry.git, so I guess that would need to be moved, too.

`npm-check-updates` [does not support Bower](https://github.com/raineorshine/npm-check-updates/pull/675) anymore. Can Bower can be dropped altogether? There's a [mention](https://github.com/purescript/registry#operations) of `purs.json` manifest file but the "example" link points to [`registry-index` repository](https://github.com/purescript/registry-index/blob/main/pr/el/prelude), not to some actual example file in the package itself.

**Comment by garyb** [comment]
> This package depends on https://github.com/keijokapp/purescript-web-geometry.git, so I guess that would need to be moved, too.

Please feel free to move that also :+1:
